In [1]:
import numpy as np

In [2]:
import pandas

In [3]:
dataset=pandas.read_csv('Marks.csv')

In [4]:
dataset

Name  Duration  Marks
0  Abhi         4     40
1  Eric         6     60
2  Jack         2     20
3  Amit         6     60

In [5]:
import cv2

In [6]:
y=dataset["Marks"]

In [7]:
x=dataset["Duration"]

In [8]:
type(x)

pandas.core.series.Series

In [9]:
X=x.values.reshape(4,1)

In [10]:
X.shape

(4, 1)

In [12]:
type(X)

numpy.ndarray

model=LinearRegression()

In [23]:
dataset

Name  Duration  Marks
0  Abhi         4     40
1  Eric         6     60
2  Jack         2     20
3  Amit         6     60

In [20]:
from sklearn.linear_model import LinearRegression

In [25]:
model=LinearRegression()

In [26]:
model.fit(X , y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
model.predict([[3]])

array([30.])

In [31]:
cv2.imread('image.jpeg')

array([[[ 62,  85, 237],
        [ 62,  85, 237],
        [ 62,  85, 237],
        ...,
        [ 65,  89, 238],
        [ 68,  93, 239],
        [ 70,  95, 241]],

       [[ 62,  85, 237],
        [ 62,  85, 237],
        [ 62,  85, 237],
        ...,
        [ 63,  87, 236],
        [ 66,  91, 237],
        [ 68,  93, 239]],

       [[ 62,  85, 237],
        [ 62,  85, 237],
        [ 62,  85, 237],
        ...,
        [ 61,  85, 234],
        [ 64,  89, 235],
        [ 66,  91, 237]],

       ...,

       [[165, 186, 117],
        [167, 188, 119],
        [179, 200, 131],
        ...,
        [178, 201, 127],
        [182, 205, 131],
        [186, 209, 135]],

       [[162, 183, 115],
        [161, 182, 114],
        [174, 195, 127],
        ...,
        [178, 201, 127],
        [182, 205, 131],
        [186, 209, 135]],

       [[167, 188, 120],
        [154, 175, 107],
        [160, 181, 113],
        ...,
        [179, 202, 128],
        [182, 205, 131],
        [187, 210, 136]]

In [35]:
photo=cv2.imread('image.jpeg')
cv2.imshow('Title_here',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
B,G,R=cv2.split(photo)

In [42]:
B.dtype

dtype('uint8')

In [43]:
R.dtype

dtype('uint8')

In [58]:
R=R.astype('uint8')

In [59]:
R.dtype

dtype('uint8')

In [61]:
photo=cv2.imread('image.jpeg')
cv2.imshow('Title_here',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [62]:
B,G,R=cv2.split(photo)

In [63]:
B

array([[ 62,  62,  62, ...,  65,  68,  70],
       [ 62,  62,  62, ...,  63,  66,  68],
       [ 62,  62,  62, ...,  61,  64,  66],
       ...,
       [165, 167, 179, ..., 178, 182, 186],
       [162, 161, 174, ..., 178, 182, 186],
       [167, 154, 160, ..., 179, 182, 187]], dtype=uint8)

In [2]:
import cv2
cap=cv2.VideoCapture(0)
status,photo=cap.read()


<VideoCapture 000001ED2AED15B0>